using System.IO;
using AuthService.Application.Common.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;

namespace AuthService.Application.Features.Auth.Login;

public sealed class ResendTwoFactorLoginCodeCommandHandler : IRequestHandler<ResendTwoFactorLoginCodeCommand, ResendTwoFactorCodeResultDto>
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IEmailService _emailService;
    private readonly ILogger<ResendTwoFactorLoginCodeCommandHandler> _logger;

    public ResendTwoFactorLoginCodeCommandHandler(
        UserManager<ApplicationUser> userManager,
        IEmailService emailService,
        ILogger<ResendTwoFactorLoginCodeCommandHandler> logger)
    {
        _userManager = userManager;
        _emailService = emailService;
        _logger = logger;
    }

    public async Task<ResendTwoFactorCodeResultDto> Handle(ResendTwoFactorLoginCodeCommand request, CancellationToken cancellationToken)
    {
        var user = await _userManager.FindByEmailAsync(request.Email)
            ?? throw new InvalidOperationException("User not found.");

        // Verify the two-factor token matches (security check)
        if (user.SecurityStamp != request.TwoFactorToken)
        {
            throw new InvalidOperationException("Invalid or expired two-factor session.");
        }

        // Only resend if using email-based 2FA (not authenticator)
        if (user.AuthenticatorEnabled)
        {
            throw new InvalidOperationException("Authenticator codes are generated by your app and cannot be resent.");
        }

        // Issue #1 FIX: DO NOT update security stamp when resending!
        // UpdateSecurityStampAsync invalidates ALL previous 2FA codes because the code
        // generation uses the security stamp as entropy. By NOT updating the stamp,
        // the new code will also work with the same TwoFactorToken the client has.
        // The old code will naturally expire after ~3 minutes anyway (Identity default).
        
        // Use the existing security stamp - this ensures the client's TwoFactorToken remains valid
        var existingSecurityStamp = user.SecurityStamp!;

        // Generate a new 2FA code (this code is bound to the current security stamp)
        var emailCode = await _userManager.GenerateTwoFactorTokenAsync(user, TokenOptions.DefaultEmailProvider);

        // Send the code via email
        await SendTwoFactorCodeEmailAsync(user, emailCode, cancellationToken);

        _logger.LogInformation("Two-factor code resent to {Email} (security stamp unchanged)", user.Email);

        // Return the SAME security stamp - client already has this token
        return new ResendTwoFactorCodeResultDto(
            NewTwoFactorToken: existingSecurityStamp,
            Message: "New verification code sent! Enter this code to continue."
        );
    }

    private async Task SendTwoFactorCodeEmailAsync(
        ApplicationUser user,
        string code,
        CancellationToken cancellationToken)
    {
        try
        {
            // Prepare user's full name
            var fullName = $"{user.FirstName} {user.LastName}".Trim();
            if (string.IsNullOrWhiteSpace(fullName))
            {
                fullName = user.Email ?? "User";
            }

            // Get current date and time
            var requestDateTime = DateTime.UtcNow;
            var requestTime = requestDateTime.ToString("MMMM dd, yyyy hh:mm tt") + " UTC";

            // Load email template
            var baseDir = AppContext.BaseDirectory;
            var templatePath = Path.Combine(baseDir, "EmailTemplates", "mail-twofactor-code.html");

            if (!File.Exists(templatePath))
            {
                _logger.LogWarning("Two-factor code email template not found at {TemplatePath}. Sending plain email instead.", templatePath);

                // Fallback to plain email
                await _emailService.SendAsync(
                    user.Email!,
                    "Your Two-Factor Authentication Code",
                    $"Your security code is: {code}. This code will expire in 5 minutes.",
                    cancellationToken);

                return;
            }

            var html = await File.ReadAllTextAsync(templatePath, cancellationToken);

            // Replace placeholders in template
            html = html.Replace("John Doe", fullName);
            html = html.Replace("{{TwoFactorCode}}", code);
            html = html.Replace("{{UserEmail}}", user.Email ?? "");
            html = html.Replace("{{RequestTime}}", requestTime);
            html = html.Replace("{{IpAddress}}", "System Generated");
            html = html.Replace("{{SupportUrl}}", "mailto:support@example.com");

            // Extract domain from user email for support email
            var emailDomain = user.Email?.Split('@').LastOrDefault() ?? "example.com";
            html = html.Replace("support@example.com", $"support@{emailDomain}");

            // Send the email
            await _emailService.SendAsync(
                user.Email!,
                "Your Two-Factor Authentication Code (Resent)",
                html,
                cancellationToken);

            _logger.LogInformation(
                "Two-factor code email resent successfully to {Email} for user {UserId}",
                user.Email,
                user.Id);
        }
        catch (Exception ex)
        {
            // Log the error but don't fail the code generation operation
            _logger.LogError(
                ex,
                "Failed to resend two-factor code email to {Email} for user {UserId}",
                user.Email,
                user.Id);

            // Re-throw to ensure the user knows the email failed
            throw;
        }
    }
}